// services/auth-service.ts
// Reusable Google OAuth sign-in for Packly.
//
// Flow (official Supabase + Expo PKCE pattern):
//   1. supabase.auth.signInWithOAuth() returns a Google authorization URL
//   2. The URL opens in a browser (Chrome Custom Tab / SFSafariViewController)
//   3. Google redirects to Supabase's callback, which redirects back to the app
//      using the native redirect URI generated by makeRedirectUri()
//   4. We extract the auth code from the returned URL and exchange it for a session
//
// Security notes:
//   - The Google Client Secret NEVER appears in this app. Supabase holds it
//     server-side and performs the token exchange — the app only ever sees the
//     authorization code.
//   - makeRedirectUri() uses the "packly" scheme from app.json with an explicit
//     callback path (→ "packly://auth/callback") in dev/production builds, and an
//     "exp://..." URL while running in Expo Go. The exact value must be added to
//     Supabase → Authentication → URL Configuration.

import * as WebBrowser from 'expo-web-browser';
import * as Linking from 'expo-linking';
import { makeRedirectUri } from 'expo-auth-session';
import { supabase } from '@/services/supabase';

// Lets the OAuth flow finish if the app was backgrounded mid-sign-in.
WebBrowser.maybeCompleteAuthSession();

export interface GoogleSignInResult {
  ok: boolean;
  /** Human-readable error message. Present when ok === false. */
  error?: string;
  /** True when the user closed the Google page without signing in. */
  cancelled?: boolean;
}

/** Maps raw OAuth errors to friendly, non-technical messages. */
function toGoogleError(message: string | undefined, fallback: string): string {
  const msg = (message ?? '').toLowerCase();
  if (
    msg.includes('network') ||
    msg.includes('fetch') ||
    msg.includes('timeout') ||
    msg.includes('econnrefused')
  ) {
    return 'Unable to connect. Please check your internet connection and try again.';
  }
  if (msg.includes('redirect_uri') || msg.includes('redirect uri')) {
    return 'Google sign-in is not configured correctly yet. Please try again later.';
  }
  if (msg.includes('invalid_client') || msg.includes('invalid client')) {
    return 'Google sign-in is not configured correctly yet. Please try again later.';
  }
  return fallback;
}

/**
 * Signs the user in with Google using the PKCE OAuth flow.
 * Returns { ok: true } on success, or { ok: false, error } / { ok: false, cancelled: true }.
 */
export async function signInWithGoogle(): Promise<GoogleSignInResult> {
  // Build the redirect URI the app returns to after Google sign-in.
  // An explicit callback path (packly://auth/callback) is used instead of the bare
  // scheme (packly://) — a query-string redirect to a scheme-only URI
  // (packly://?code=...) can be mishandled on Android, while a path-based
  // redirect (packly://auth/callback?code=...) is the documented, reliable form.
  // This exact value must be listed in Supabase → Authentication → URL Configuration.
  const redirectTo = makeRedirectUri({ path: 'auth/callback' });

  // Debug aid: print the exact redirect URI so it can be registered in Supabase.
  if (__DEV__) {
    console.log('[Google OAuth] redirectTo =', redirectTo);
  }

  // 1. Ask Supabase to build the Google authorization URL.
  const { data, error } = await supabase.auth.signInWithOAuth({
    provider: 'google',
    options: {
      redirectTo,
      skipBrowserRedirect: true,
    },
  });

  if (error) {
    if (__DEV__) {
      console.log('[Google OAuth] signInWithOAuth failed:', error.message);
    }
    return {
      ok: false,
      error: toGoogleError(error.message, 'Unable to start Google sign-in. Please try again.'),
    };
  }
  if (!data?.url) {
    return { ok: false, error: 'Unable to start Google sign-in. Please try again.' };
  }

  // Debug aid: print the redacted authorization URL so we can confirm the
  // callback is embedded exactly as Supabase must see it, e.g.
  //   redirect_to=packly%3A%2F%2Fauth%2Fcallback
  if (__DEV__) {
    const redactedAuthUrl = data.url.replace(
      /([?&#](?:code|verifier|token|state|refresh_token|access_token|id_token|code_challenge)=)[^&#]*/gi,
      '$1[REDACTED]',
    );
    console.log('[Google OAuth] authorization URL:', redactedAuthUrl);
  }

  // 2. Open Google's login page and wait for the redirect back to the app.
  // Known Android issue (expo/expo#23781, expo/expo#6289): on Android,
  // openAuthSessionAsync resolves 'dismiss' the moment the app returns to
  // foreground — BEFORE the deep-link event arrives — even when the login
  // succeeded. The documented workaround is to ALSO capture the redirect URL
  // via a Linking listener and keep waiting for it after a dismiss.
  // A user-initiated 'cancel' (pressing back) is never treated as success.
  let capturedRedirectUrl: string | null = null;
  const linkingSubscription = Linking.addEventListener('url', (event) => {
    if (event.url.startsWith(redirectTo)) {
      capturedRedirectUrl = event.url;
    }
  });

  // If the OS killed the app while the browser was open, the redirect URL is
  // delivered as the app's initial URL on relaunch instead of a 'url' event.
  // Pre-seed the capture so a cold-start deep link is never missed.
  try {
    const initialUrl = await Linking.getInitialURL();
    if (initialUrl && initialUrl.startsWith(redirectTo)) {
      capturedRedirectUrl = initialUrl;
    }
  } catch {
    // getInitialURL can throw on some platforms; the event listener covers it.
  }

  let result: WebBrowser.WebBrowserAuthSessionResult | null = null;
  try {
    // Android: the default launch mode (createTask: true + useProxyActivity: true)
    // opens the custom tab in a SEPARATE task via a proxy activity. On devices
    // that show Google's device-verification (fingerprint) prompt, the OS can
    // destroy that tab before the redirect fires, showing 'dismiss' with no URL.
    // showInRecents: true keeps the custom tab in the recents list so the OS is
    // far less likely to kill it while the fingerprint prompt is up.
    // See expo/expo#23781 and the r/expo community fix. Runtime option only —
    // no native rebuild required.
    result = await WebBrowser.openAuthSessionAsync(data.url, redirectTo, {
      showInRecents: true,
    });

    // If the promise resolved 'dismiss'/'opened'/'cancel' without a URL, the
    // deep link may still be in flight (Android dismiss race). Wait for it in
    // short polls instead of giving up immediately.
    if (capturedRedirectUrl === null && (result.type !== 'success' || !result.url)) {
      for (let waited = 0; waited < 50; waited++) {
        await new Promise((resolve) => setTimeout(resolve, 100));
        if (capturedRedirectUrl !== null) break;
      }
    }
  } catch (err) {
    const message = err instanceof Error ? err.message : undefined;
    return { ok: false, error: toGoogleError(message, 'Unable to open Google sign-in. Please try again.') };
  } finally {
    linkingSubscription.remove();
  }

  // Prefer the deep link captured by Linking (reliable on Android); fall back
  // to the browser promise's URL (reliable on iOS).
  const redirectUrl = capturedRedirectUrl ?? (result?.type === 'success' ? result.url : null);

  if (!redirectUrl) {
    if (result?.type === 'cancel' || result?.type === 'dismiss') {
      if (__DEV__) {
        console.log('[Google OAuth] openAuthSessionAsync returned:', { type: result?.type });
      }
      return { ok: false, cancelled: true };
    }
    // 'opened' / 'locked' — the browser opened but we did not get a redirect back.
    if (__DEV__) {
      console.log('[Google OAuth] openAuthSessionAsync returned:', { type: result?.type });
    }
    return { ok: false, error: 'Google sign-in did not complete. Please try again.' };
  }

  if (__DEV__) {
    // Redact anything sensitive (auth codes, verifiers, tokens, state) before logging.
    const redactedUrl = redirectUrl.replace(
      /([?&#](?:code|verifier|token|state|refresh_token|access_token|id_token)=)[^&#]*/gi,
      '$1[REDACTED]',
    );
    console.log('[Google OAuth] redirect received:', {
      url: redactedUrl,
      hasCode: /[?#&]code=/.test(redirectUrl),
    });
  }

  // 3. User denied permission on Google's consent screen (distinct from closing
  //    the browser, which returns type 'cancel'). Treat it as a clean cancel.
  if (/[?#&]error=access_denied/.test(redirectUrl)) {
    return { ok: false, cancelled: true };
  }

  // 4. Extract the authorization code (query or fragment) and exchange it for a session.
  const code = redirectUrl.match(/[?#&]code=([^&]+)/)?.[1];
  if (__DEV__) {
    console.log('[Google OAuth] extracted code:', code ? `yes (${code.length} chars)` : 'NO');
  }
  if (!code) {
    // Debug aid: if this fires, the app returned without an auth code — usually the
    // redirect URI below isn't registered in Supabase → Authentication → URL Configuration.
    if (__DEV__) {
      console.log('[Google OAuth] no code found in returned URL:', redirectUrl);
    }
    return { ok: false, error: 'Unable to complete Google sign-in. Please try again.' };
  }

  const { error: exchangeError } = await supabase.auth.exchangeCodeForSession(code);
  if (exchangeError) {
    // Debug aid: prints the FULL Supabase error (message, status, code) so the root
    // cause isn't hidden behind the friendly message.
    if (__DEV__) {
      const authError = exchangeError as { status?: number; code?: string };
      console.log('[Google OAuth] code exchange failed:', {
        message: exchangeError.message,
        status: authError.status,
        code: authError.code,
      });
    }
    return {
      ok: false,
      error: toGoogleError(
        exchangeError.message,
        'Unable to complete Google sign-in. Please try again.',
      ),
    };
  }

  if (__DEV__) {
    console.log('[Google OAuth] code exchange succeeded');
  }

  return { ok: true };
}
