-- Packly Database Migration
-- Version: 015
-- Description: In-app account deletion (store-policy requirement) done as a
-- TOMBSTONE, not a hard delete.
--
--   The user experience is "my account is gone": sign-in is rejected forever
--   and the app treats them as deleted. Under the hood the rows survive:
--
--     • auth.users row KEPT, banned_until = 'infinity'
--         GoTrue rejects every sign-in for banned users (password, Google,
--         magic link — everything). The row also keeps the original email
--         RESERVED: Supabase rejects sign-up with an in-use email, so a
--         deleted account's email can never re-sign-up and collect another
--         round of free signup credits. (banned_until is written directly —
--         the same column the dashboard's "Ban user" sets; it blocks sign-in
--         but leaves the row in place.)
--     • public.users row KEPT, email rewritten to a tombstone address
--         'deleted+<confirm>@packly.invalid' so the real email is not
--         leaked through the users table either.
--     • moves / rooms / boxes / items KEPT
--         Collaborators on shared moves keep their inventory; the owner can
--         never sign back in to touch it.
--     • CREDITS ZEROED (with an exact ledger trail)
--         Any remaining free or pro balance is wiped at deletion, so
--         deletion cannot be used as a "reset my credits" button.
--
--   A real hard delete stays possible later via the dashboard (deleting the
--   auth user cascades everywhere — migration 012), or a support-triggered
--   purge job. Nothing here blocks that.

-- ============================================
-- 1) users.deleted_at — tombstone timestamp for audits/support
-- ============================================
ALTER TABLE public.users
  ADD COLUMN IF NOT EXISTS deleted_at timestamptz;

-- ============================================
-- 2) delete_account(p_confirm) — called by the app's Delete Account flow.
--    p_confirm is a random token generated by the client per attempt; it is
--    only used to make the tombstone email collision-proof between attempts.
--    Runs as the caller (auth.uid()) but elevated via SECURITY DEFINER to
--    reach auth.users, which RLS/permissions otherwise hide.
-- ============================================
CREATE OR REPLACE FUNCTION public.delete_account(p_confirm text)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
DECLARE
  v_uid  uuid := auth.uid();
  v_free int;
  v_pro  int;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'NOT_AUTHENTICATED';
  END IF;

  IF p_confirm IS NULL OR length(p_confirm) < 8 THEN
    RAISE EXCEPTION 'INVALID_CONFIRM';
  END IF;

  -- ── 1) Wipe credit balances with an exact ledger trail ──
  -- Read BEFORE zeroing so SUM(delta) per bucket keeps matching the balance
  -- (the 014 invariant).
  SELECT COALESCE(free_balance, 0), COALESCE(pro_balance, 0)
    INTO v_free, v_pro
    FROM public.user_credits
   WHERE user_id = v_uid;

  IF COALESCE(v_free, 0) > 0 THEN
    INSERT INTO public.credit_ledger (user_id, delta, reason, bucket)
    VALUES (v_uid, -v_free, 'account_deleted', 'free');
  END IF;

  IF COALESCE(v_pro, 0) > 0 THEN
    INSERT INTO public.credit_ledger (user_id, delta, reason, bucket)
    VALUES (v_uid, -v_pro, 'account_deleted', 'pro');
  END IF;

  UPDATE public.user_credits
     SET free_balance   = 0,
         pro_balance    = 0,
         pro_expires_at = NULL,
         updated_at     = now()
   WHERE user_id = v_uid;

  -- ── 2) Tombstone the profile row ──
  -- Keep the row (shared moves still reference it) but free the email and
  -- mark the deletion time. The token keeps repeat deletes from colliding.
  UPDATE public.users
     SET email      = 'deleted+' || left(p_confirm, 12) || '@packly.invalid',
         deleted_at = now()
   WHERE id = v_uid;

  -- ── 3) Ban the auth user — the "deleted" the user actually sees ──
  -- Blocks ALL sign-in methods forever. The row stays, so the original
  -- email remains reserved (no re-signup → no free-credit farming) and a
  -- dashboard hard delete is still one click away.
  UPDATE auth.users
     SET banned_until = 'infinity'::timestamptz
   WHERE id = v_uid;
END;
$$;

REVOKE EXECUTE ON FUNCTION public.delete_account(text)
  FROM PUBLIC, anon;
GRANT EXECUTE ON FUNCTION public.delete_account(text)
  TO authenticated;

-- ============================================
-- 3) Signup guard — defense in depth for the anti-farm rule.
--    GoTrue already rejects sign-up with an in-use email, but this catches
--    edge paths (dashboard-created users, future email handling changes):
--    if a NEW auth user arrives with the email of an already-tombstoned
--    profile, refuse to create their public row. The masked GoTrue error
--    ("Database error saving new user") is mapped to a friendly message in
--    the app (lib/errors.ts).
-- ============================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER SET search_path = ''
AS $$
BEGIN
  -- Email belongs to an account the user themselves deleted → do not
  -- resurrect it (that would re-grant signup credits).
  IF EXISTS (
    SELECT 1 FROM public.users u
     WHERE lower(u.email) = lower(NEW.email)
       AND u.email LIKE 'deleted+%@packly.invalid'
  ) THEN
    RAISE EXCEPTION 'ACCOUNT_PERMANENTLY_DELETED';
  END IF;

  INSERT INTO public.users (id, name, email, created_at)
  VALUES (
    NEW.id,
    COALESCE(NEW.raw_user_meta_data ->> 'name', split_part(NEW.email, '@', 1)),
    NEW.email,
    COALESCE(NEW.created_at, NOW())
  )
  ON CONFLICT (id) DO NOTHING;
  RETURN NEW;
END;
$$;

-- ============================================
-- Reversal (run to undo this migration)
-- ============================================
-- ALTER TABLE public.users DROP COLUMN IF EXISTS deleted_at;
-- DROP FUNCTION IF EXISTS public.delete_account(text);
-- (then re-apply 002's version of handle_new_user)
